name: Deploy to Firebase Hosting

on:
  push:
    branches:
      # - main
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: |
          npm run build
          npx next export

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase (staging or prod)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ "${GITHUB_REF##*/}" == "yetToBeDecided" ]; then
            echo "Deploying to PROD..."
            firebase deploy --only hosting:prod --token "$FIREBASE_TOKEN"
          else
            echo "Deploying to STAGING..."
            firebase deploy --only hosting:stage --token "$FIREBASE_TOKEN"
          fi
